pub mod builder;
pub mod catalog;
pub mod contract;
pub mod error;
pub mod event;
pub mod help;
pub mod model;
pub mod registry;
pub mod response;
pub mod rmcp_adapter;
pub mod template;

pub use builder::*;
pub use catalog::*;
pub use contract::{ContractViolation, verify_catalog_coverage};
pub use error::{FrameworkError, Result};
pub use event::{EventSink, FrameworkEvent, InMemoryEventSink, NoopEventSink, PlanFacts};
pub use help::{HelpDetail, HelpRequest, HelpResult, HelpTopic};
pub use model::*;
pub use registry::{CommandHandler, CommandRegistry, HandlerFuture};
pub use response::*;
pub use rmcp_adapter::{CliMcpServer, CliMcpServerConfig};
pub use template::{CommandTemplate, TemplateToken};
